title: "SOCOVAP"
description: "L'Humain n'est qu'une variable. Optimisons-la."
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # Design blanc, pur et pro

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# On pr√©pare le terrain pour tes futurs dossiers
collections:
  services:
    output: true
  team:
    output: true
    site_navigation: main

   footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"
  # Pour enlever le "Powered by Jekyll & Minimal Mistakes" :
  disable_thanks: true 
